### ISSUE TITLE
WebUI is not available

### ISSUE THREAD

**Issue by Xornop** [baldarn/whatsapper#1]
WebUI is not available.
Installed, started, looked at log, scanned qr with whatsapp mobile app, connected according to the app.
Running hassos without docker, install instructions dont mention that docker is needed

>`
{"method":"GET","url":"/","hostname":"homeassistant.local:3456","remoteAddress":"192.168.69.103","remotePort":52300},"msg":"incoming request"}
{"level":30,"time":1706443007881,"pid":7,"hostname":"db21ed7f-whatsapper","reqId":"req-b","res":{"statusCode":200},"responseTime":3.00314599275589,"msg":"request completed"}
{"level":30,"time":1706443008217,"pid":7,"hostname":"db21ed7f-whatsapper","reqId":"req-c","req":{"method":"GET","url":"/favicon.ico","hostname":"homeassistant.local:3456","remoteAddress":"192.168.69.103","remotePort":52300},"msg":"incoming request"}
{"level":30,"time":1706443008219,"pid":7,"hostname":"db21ed7f-whatsapper","reqId":"req-c","msg":"Route GET:/favicon.ico not found"}
{"level":30,"time":1706443008225,"pid":7,"hostname":"db21ed7f-whatsapper","reqId":"req-c","res":{"statusCode":404},"responseTime":7.172524988651276,"msg":"request completed"}
`

**Comment by baldarn** [comment]
hi, thanks for the issue.

webui on the / path is not present.

you can navigate to /chats to see a little webui.

for not the app is intended to be used through post at /command api :)

**Comment by Xornop** [comment]
Going to homeassistant.local:4000/chats gives me:

{"error":"Client not initalized"}

Please update the installation instructions for dummies like me

**Comment by baldarn** [comment]
for HA I created this
https://github.com/baldarn/whatsapper-ha-integration

is also in the process of being merged in hacs, hopefully ;)

**Comment by Xornop** [comment]
Going to homeassistant.local:4000/chats still gives me:
{"error":"Client not initalized"}
Please help.

**Comment by baldarn** [comment]
how are you starting the app?
have you scanned the qr code?

**Comment by Xornop** [comment]
By pressing start in the whatsapper add-on menu.
I have scanned the qr which appears in the log.

**Comment by baldarn** [comment]
yes, I thought that was already done, but I was wrong ;)

I'll try to implement that.

https://github.com/baldarn/whatsapper/issues/2

**Comment by baldarn** [comment]
@Xornop fixed here

https://github.com/baldarn/whatsapper/issues/2
