### ISSUE TITLE
Sample to send message

### ISSUE THREAD

**Issue by DEVIDTR** [baldarn/whatsapper#3]
Hi,

I am not able to send a massage using curl:

curl -H "Content-Type: application/json" -X POST -d '{"command":"sendMessage","params": ["Hello @PHONE_NUMBER"]}' http://IP:4000/command

Do I miss something?

**Comment by baldarn** [comment]
hi, for the function `sendMessage` you must pass 2 parameters: the `chat_id` and the `message`

try this ;0
