### ISSUE TITLE
Support images from notifications

### ISSUE THREAD

**Issue by ssorgatem** [baldarn/whatsapper#5]
It'd be nice to support HA notifications with images like the Android companion app, e.g. for camera snapshots from frigate and such.

It seems the underlying Js library does support sending images.

**Comment by baldarn** [comment]
thanks for your time!

I will try and see how this can be obtained ;)

**Comment by baldarn** [comment]
this https://github.com/baldarn/whatsapper/commit/adffb81ef5e481a0773cf6e8750a13cdd73c6834 add the function
